export const RENDER_CONFIG = {
    fontSize: 14,
    fontHeightMult: 1.15,
    bgColor: '#111',
    cursorBg: '#444',
    selectionBgZone: '#2a3a2a',
    selectionBgBuild: '#3a2a2a',
    nightMaxDarkness: 0.55,
    nightDawnDuskOffset: { duskEnd: 0.12, dawnStart: 0.10 },
    nightGradientSteps: 8,
    nightOverlayColor: [0, 0, 20],
    lightSourceMargin: 8,
    fireLightRadius: 2,
    seasonDaylight: {
        summer: { dawn: 0.15, dusk: 0.75 },
        winter: { dawn: 0.25, dusk: 0.65 },
        spring: { dawn: 0.18, dusk: 0.72 },
        autumn: { dawn: 0.22, dusk: 0.68 },
        default: { dawn: 0.20, dusk: 0.70 },
    },
    terrainDithering: true,
    ditherDepth: 0.3,
    draftedPulsePeriod: 20,
    draftedPulseDuty: 10,
    spellGlowPeriod: 16,
    spellGlowDuty: 8,
    riftPulsePeriod: 20,
    riftPulseDuty: 10,
    healthBarGreenThreshold: 0.5,
    healthBarYellowThreshold: 0.25,
    healthBarColors: { green: '#00ff00', yellow: '#ffaa00', red: '#ff3333' },
    buildGridColor: 'rgba(255, 140, 0, 1)',
};

export const COMBAT_VISUALS = {
    hitChar: '!',
    hitColor: '#ffff00',
    hitTtl: 2,
    damageTakenColor: '#ff3333',
    nexusDamageColor: '#9933ff',
    structureDamageColor: '#ff8800',
    portalChar: 'Ø',
    portalColor: '#ff55ff',
    portalBg: '#440044',
    portalPathColor: '#663388',
    portalPathBg: '#1a001a',
    shotColorArcane: '#ff4444',
    shotColorVoid: '#cc00ff',
    spellHealChar: '+',
    spellHealColor: '#44ff44',
    spellBuffChar: '>',
    spellBuffColor: '#88ffff',
    spellShieldChar: 'O',
    spellShieldColor: '#4488ff',
    spellTeleportChar: '@',
    spellTeleportColor: '#33ccff',
    spellGrowthChar: '%',
    spellGrowthColor: '#44ff44',
    spellTerraformChar: '.',
    spellTerraformColor: '#88ff88',
    spellDivinationChar: '?',
    spellDivinationColor: '#ccaaff',
    spellRangePreviewBg: '#1a0033',
    magicLevelUpChar: '★',
    magicLevelUpTtl: 5,
    dmgFlashTtl: 2,
    dmgFlashColor: '#ff2222',
    dmgFlashAlpha: 0.4,
    atkShakeTtl: 2,
    atkShakePx: 2,
    spellCastChar: '◇',
    spellCastColor: '#cc88ff',
    projectileSpeed: 12,
    projectileChar: '•',
    craftCompleteChar: '✧',
    craftCompleteColor: '#ffcc44',
    craftCompleteTtl: 4,
    needCriticalChar: '!',
    needCriticalColor: '#ff4444',
    needCriticalTtl: 6,
    sleepChar: 'z',
    sleepColor: '#6688cc',
    sleepTtl: 8,
    healthRegenChar: '♥',
    healthRegenColor: '#66ff66',
    healthRegenTtl: 2,
    healTickChar: '+',
    healTickColor: '#44ff44',
    healTickTtl: 2,
    researchCompleteChar: '!',
    researchCompleteColor: '#44ffff',
    researchCompleteTtl: 6,
    buildCompleteChar: '✓',
    buildCompleteColor: '#ffffff',
    buildCompleteTtl: 4,
    harvestChar: '⌂',
    harvestColor: '#66cc44',
    harvestTtl: 3,
    mentalBreakChar: '☠',
    mentalBreakColor: '#cc2222',
    mentalBreakTtl: 8,
    freezingChar: '~',
    freezingColor: '#88ddff',
    freezingTtl: 4,
    mineDustChar: '·',
    mineDustColor: '#999999',
    mineDustTtl: 2,
    shieldBlockChar: '○',
    shieldBlockColor: '#4488ff',
    shieldBlockTtl: 3,
    manaRegenChar: '∴',
    manaRegenColor: '#aa66ff',
    manaRegenTtl: 2,
    deathChar: '☠',
    deathColor: '#ffffff',
    deathTtl: 10,
    summonArriveChar: '◊',
    summonArriveColor: '#cc44ff',
    summonArriveTtl: 5,
    lootDropChar: '$',
    lootDropColor: '#ffdd44',
    lootDropTtl: 5,
    fireIgniteChar: '^',
    fireIgniteColor: '#ff6600',
    fireIgniteTtl: 3,
    waveAlertTtl: 8,
    waveAlertColor: '#ff2222',
    golemActivateChar: '⚡',
    golemActivateColor: '#44ffff',
    golemActivateTtl: 6,
    xpGainChar: '·',
    xpGainColor: '#88ff88',
    xpGainTtl: 1,
};

export const LOG_COLORS = {
    danger: '#ff5555',
    combat: '#ff8844',
    success: '#88ff88',
    loot: '#ffcc44',
    ambient: '#777777',
    default: '#aaddff',
};
